import pyvisa

class keysight_33600a():

	def __init__(self, pyvisa_resource):
		self.key33600a = pyvisa_resource

	def get_all_scpi_dict(self):
		result_dict = {}
		for command in self.scpi_cmd_dict:
			result = (self.key33600a.query(command.format("?"))).rstrip('\r\n')
#			print("'" + command.format(" ") + str(result) + "',")
			result = " " + result
			result_dict[command.format("?")] = result
		return result_dict

	def get_all_scpi_list(self):
		result_list = []
		for command in self.scpi_cmd_dict:
#			print(str(command) + "\n")
			result = (self.key33600a.query(command.format("?"))).rstrip('\r\n')
			result = " " + result
			result_list.append(command.format(result))
		return result_list

	def get_unique_scpi_list(self):
		unique_scpi_list = []
		inst_settings_list = self.get_all_scpi_list()
		for setting in inst_settings_list:
			if (setting not in self.settings_por_scpi_list):
				unique_scpi_list.append(setting)
		return unique_scpi_list
	
	scpi_cmd_dict = { 
	                  "SOURce1:AM:DEPTh{0}"                          : "<depth_in_percent>|MINimum|MAXimum",
	                  "SOURce1:AM:DSSC{0}"                           : "ON|1|OFF|0",
	                  "SOURce1:AM:INTernal:FREQuency{0}"             : "<frequency>|MINimum|MAXimum|DEFault",
	                  "SOURce1:AM:INTernal:FUNCtion{0}"              : "SINusoid|SQUare|RAMP|NRAMp|TRIangle|NOISe|PRBS|ARB",
	                  "SOURce1:AM:SOURce{0}"                         : "INTernal|EXTernal|CH1|CH2",
	                  "SOURce1:BPSK:SOURce{0}"                       : "INTernal|EXTernal",
	                  "SOURce1:FM:SOURce{0}"                         : "INTernal|EXTernal|CH1|CH2",
	                  "SOURce1:FSKey:SOURce{0}"                      : "INTernal|EXTernal",
	                  "SOURce1:PM:SOURce{0}"                         : "INTernal|EXTernal|CH1|CH2",
	                  "SOURce1:PWM:SOURce{0}"                        : "INTernal|EXTernal|CH1|CH2",
	                  "SOURce1:AM:STATe{0}"                          : "ON|1|OFF|0",
	                  "SOURce1:BPSK:STATe{0}"                        : "ON|1|OFF|0",
	                  "SOURce1:FM:STATe{0}"                          : "ON|1|OFF|0",
	                  "SOURce1:FSKey:STATe{0}"                       : "ON|1|OFF|0",
	                  "SOURce1:PM:STATe{0}"                          : "ON|1|OFF|0",
	                  "SOURce1:PWM:STATe{0}"                         : "ON|1|OFF|0",
#	                  "SOURce1:APPLy:{0}"                            : "function> [<frequency> [,<amplitude> [,<offset>]]]",
                      "SOURce1:BPSK:INTernal:RATE{0}"                : "<modulating_frequency>|MINimum|MAXimum|DEFault",
                      "SOURce1:BPSK:PHASe{0}"                        : "<angle>|MINimum|MAXimum|DEFault",
                      "SOURce1:BURSt:GATE:POLarity{0}"               : "NORMal|INVerted",
                      "SOURce1:BURSt:INTernal:PERiod{0}"             : "<seconds>|MINimum|MAXimum",
                      "SOURce1:BURSt:MODE{0}"                        : "TRIGgered|GATed",
                      "SOURce1:BURSt:NCYCles{0}"                     : "<num_cycles>|INFinity|MINimum|MAXimum",
                      "SOURce1:BURSt:PHASe{0}"                       : "<angle>|MINimum|MAXimum",
                      "SOURce1:BURSt:STATe{0}"                       : "ON|1|OFF|0",
#	                  "SOURce1:COMBine:FEED{0}"                      : "CH1|CH2|NONE",
                      "DISPlay{0}"                                   : "ON|1|OFF|0",
                      "SOURce1:FM:DEViation{0}"                      : "<peak_deviation_in_Hz>|MINimum|MAXimum|DEFault",
                      "SOURce1:FM:INTernal:FREQuency{0}"             : "<frequency>|MINimum|MAXimum|DEFault",
                      "SOURce1:FM:INTernal:FUNCtion{0}"              : "SINusoid|SQUare|RAMP|NRAMp|TRIangle|NOISe|PRBS|ARB",
                      "FORMat:BORDer{0}"                             : "NORMal|SWAPped",
                      "SOURce1:FREQuency{0}"                         : "<frequency>|MINimum|MAXimum|DEFault",
                      "SOURce1:FREQuency:CENTer{0}"                  : "<frequency>|MINimum|MAXimum|DEFault",
#	                  "SOURce1:FREQuency:COUPle:STATe{0}"            : "ON|1|OFF|0",
#	                  "SOURce1:FREQuency:COUPle:MODE{0}"             : "OFFSet|RATio",
#	                  "SOURce1:FREQuency:COUPle:OFFSet{0}"           : "<frequency>|MINimum|MAXimum|DEFault",
#	                  "SOURce1:FREQuency:COUPle:RATio{0}"            : "<ratio>",
	                  "SOURce1:FREQuency:MODE{0}"                    : "CW|LIST|SWEep|FIXed",
	                  "SOURce1:FREQuency:SPAN{0}"                    : "<frequency>|MINimum|MAXimum|DEFault",
	                  "SOURce1:FREQuency:STARt{0}"                   : "<frequency>|MINimum|MAXimum|DEFault",
	                  "SOURce1:FREQuency:STOP{0}"                    : "<frequency>|MINimum|MAXimum|DEFault",
	                  "SOURce1:FSKey:FREQuency{0}"                   : "<frequency>|MINimum|MAXimum|DEFault",
	                  "SOURce1:FSKey:INTernal:RATE{0}"               : "<rate_in_Hz>|MINimum|MAXimum",
	                  "SOURce1:FUNCtion{0}"                          : "SINusoid|SQUare|TRIangle|RAMP|PULSe|PRBS|NOISe|ARB|DC",
	                  "SOURce1:FUNCtion:ARBitrary{0}"                : "<filename>",
	                  "SOURce1:FUNCtion:ARBitrary:ADVance{0}"        : "TRIGger|SRATe",
	                  "SOURce1:FUNCtion:ARBitrary:FILTer{0}"         : "NORMal|STEP|OFF",
	                  "SOURce1:FUNCtion:ARBitrary:FREQuency{0}"      : "<frequency>|MINimum|MAXimum|DEFault",
	                  "SOURce1:FUNCtion:ARBitrary:PERiod{0}"         : "<period>|MINimum|MAXimum}DEFault",
	                  "SOURce1:FUNCtion:ARBitrary:PTPeak{0}"         : "<voltage>|MINimum|MAXimum|DEFault",
	                  "SOURce1:FUNCtion:ARBitrary:SRATe{0}"          : "<sample_rate>|MINimum|MAXimum|DEFault",
	                  "SOURce1:FUNCtion:NOISe:BANDwidth{0}"          : "<bandwidth>|MINimum|MAXimum|DEFault",
	                  "SOURce1:FUNCtion:PRBS:BRATe{0}"               : "<bit_rate>|MINimum|MAXimum|DEFault",
	                  "SOURce1:FUNCtion:PRBS:DATA{0}"                : "PN3 through PN32",
	                  "SOURce1:FUNCtion:PRBS:TRANsition:BOTH{0}"     : "<seconds>|MINimum|MAXimum|DEFault",
#	                  "SOURce1:FUNCtion:PULSe:DCYCle{0}"             : "<percent>|MINimum|MAXimum|DEFault",
	                  "SOURce1:FUNCtion:PULSe:HOLD{0}"               : "WIDTh|DCYCle",
	                  "SOURce1:FUNCtion:PULSe:PERiod{0}"             : "<seconds>|MINimum|MAXimum|DEFault",
	                  "SOURce1:FUNCtion:PULSe:TRANsition:LEADing{0}" : "<seconds>|MINimum|MAXimum|DEFault",
	                  "SOURce1:FUNCtion:PULSe:TRANsition:TRAiling{0}": "<seconds>|MINimum|MAXimum|DEFault",
	                  "SOURce1:FUNCtion:PULSe:WIDTh{0}"              : "<seconds>|MINimum|MAXimum|DEFault",
	                  "SOURce1:FUNCtion:RAMP:SYMMetry{0}"            : "<percent>|MINimum|MAXimum|DEFault",
	                  "SOURce1:FUNCtion:SQUare:DCYCle{0}"            : "<percent>|MINimum|MAXimum",
	                  "SOURce1:FUNCtion:SQUare:PERiod{0}"            : "<seconds>|MINimum|MAXimum|DEFault",
	                  "FUNCtion:ARBitrary:BALance:STATe{0}"          : "ON|1|OFF|0",
	                  "FUNCtion:ARBitrary:BALance:GAIN{0}"           : "<percent>|MINimum|MAXimum|DEFine",
	                  "FUNCtion:ARBitrary:BALance:OFFSet1{0}"        : "<volts>|MINimum|MAXimum|DEFault",
	                  "FUNCtion:ARBitrary:BALance:OFFSet2{0}"        : "<volts>|MINimum|MAXimum|DEFault",
	                  "FUNCtion:ARBitrary:SKEW:STATe{0}"             : "ON|1|OFF|0",
	                  "FUNCtion:ARBitrary:SKEW:TIME{0}"              : "<time>|MINimum|MAXimum|DEFault",
	                  "INITiate1:CONTinuous{0}"                      : "ON|1|OFF|0",
	                  "INPut:ATTenuation:STATe{0}"                   : "ON|1|OFF|0",
	                  "SOURce1:LIST:DWELl{0}"                        : "<seconds>|MINimum|MAXimum",
	                  "SOURce1:LIST:FREQuency{0}"                    : "<freq1>[, <freq2>, etc.]",
	                  "SOURce1:MARKer:CYCle{0}"                      : "<cycle_num>|MINimum|MAXimum|DEFault",
	                  "SOURce1:MARKer:FREQuency{0}"                  : "<frequency>|MINimum|MAXimum|DEFault",
	                  "SOURce1:MARKer:POINt{0}"                      : "<sample_number>|MINimum|MAXimum",
	                  "OUTPut1:LOAD{0}"                              : "<ohms>|INFinity|MINimum|MAXimum|DEFault",
	                  "OUTPut1:MODE{0}"                              : "NORMal|GATed",
	                  "OUTPut1:POLarity{0}"                          : "NORMal|INVerted",
	                  "OUTPut:SYNC{0}"                               : "ON|1|OFF|0",
	                  "OUTPut1:SYNC:MODE{0}"                         : "NORMal|CARRier|MARKer",
	                  "OUTPut1:SYNC:POLarity{0}"                     : "NORMal|INVerted",
	                  "OUTPut:SYNC:SOURce{0}"                        : "CH1|CH2",
	                  "OUTPut:TRIGger{0}"                            : "ON|1|OFF|0",
	                  "OUTPut:TRIGger:SLOPe{0}"                      : "POSitive|NEGative",
	                  "OUTPut:TRIGger:SOURce{0}"                     : "CH1|CH2",
	                  "SOURce1:PHASe:ARBitrary{0}"                   : "<angle>|MINimum|MAXimum",
	                  "SOURce1:PHASe:MODulation{0}"                  : "<angle>|MINimum|MAXimum",
	                  "SOURce1:PM:DEViation{0}"                      : "<deviation in degrees>|MINimum|MAXimum|DEFault",
	                  "SOURce1:PM:INTernal:FREQuency{0}"             : "<frequency>|MINimum|MAXimum|DEFault",
	                  "SOURce1:PM:INTernal:FUNCtion{0}"              : "SINusoid|SQUare|RAMP|NRAMp|TRIangle|NOISe|PRBS|ARB",
	                  "SOURce1:PWM:DEViation{0}"                     : "<deviation>|MINimum|MAXimum|DEFault",
	                  "SOURce1:PWM:DEViation:DCYCle{0}"              : "<deviation_in_pct>|MINimum|MAXimum|DEFault",
	                  "SOURce1:PWM:INTernal:FREQuency{0}"            : "<frequency>|MINimum|MAXimum|DEFault",
	                  "SOURce1:PWM:INTernal:FUNCtion{0}"             : "SINusoid|SQUare|RAMP|NRAMp|TRIangle|NOISe|PRBS|ARB",
#	                  "SOURce1:RATE:COUPle:STATe{0}"                 : "ON|1|OFF|0",
#	                  "SOURce1:RATE:COUPle:MODE{0}"                  : "OFFSet|RATio",
#	                  "SOURce1:RATE:COUPle:OFFSet{0}"                : "<sample_rate>|MINimum|MAXimum|DEFault",
#	                  "SOURce1:RATe:COUPle:RATio{0}"                 : "<ratio>|MINimum|MAXimum",
	                  "ROSCillator:SOURce{0}"                        : "INTernal|EXTernal",
	                  "ROSCillator:SOURce:AUTO{0}"                   : "ON|OFF",
	                  "SOURce1:SUM:AMPLitude{0}"                     : "<amplitude>|MINimum|MAXimum|DEFault",
	                  "SOURce1:SUM:INTernal:FREQuency{0}"            : "<frequency>|MINimum|MAXimum|DEFault",
	                  "SOURce1:SUM:INTernal:FUNCtion{0}"             : "SINusoid|SQUare|RAMP|NRAMp|TRIangle|NOISe|PRBS|ARB",
	                  "SOURce1:SUM:SOURce{0}"                        : "INTernal|EXTernal|CH1|CH2",
	                  "SOURce1:SWEep:HTIMe{0}"                       : "<hold_time>|MINimum|MAXimum|DEFault",
	                  "SOURce1:SWEep:RTIMe{0}"                       : "<return_time>|MINimum|MAXimum|DEFault",
	                  "SOURce1:SWEep:SPACing{0}"                     : "LINear|LOGarithmic",
	                  "SOURce1:SWEep:STATe{0}"                       : "ON|1|OFF|0",
	                  "SOURce1:SWEep:TIME{0}"                        : "<seconds>|MINimum|MAXimum|DEFault",
#	                  "SOURce1:TRACk{0}"                             : "ON|OFF|INVerted",
	                  "TRIGger1:COUNt{0}"                            : "<number>MINimum|MAXimum|DEFault",
	                  "TRIGger1:DELay{0}"                            : "<seconds>|MINimum|MAXimum",
	                  "TRIGger1:LEVel{0}"                            : "<level>|MINimum|MAXimum",
	                  "TRIGger1:SLOPe{0}"                            : "POSitive|NEGative",
	                  "TRIGger1:SOURce{0}"                           : "IMMediate|EXTernal|TIMer|BUS",
	                  "TRIGger1:TIMer{0}"                            : "<seconds>|MINimum|MAXimum",
	                  "UNIT:ANGLe{0}"                                : "DEGree|RADian|SECond|DEFault",
	                  "UNIT:ARBitrary:ANGLe{0}"                      : "EGree|RADian|SECond|SAMPle|DEFault",
	                  "SOURce1:VOLTage{0}"                           : "<amplitude>|MINimum|MAXimum|DEFault",
#	                  "SOURce1:VOLTage:COUPle:STATe{0}"              : "ON|1|OFF|0",
	                  "SOURce1:VOLTage:HIGH{0}"                      : "<voltage>|MINimum|MAXimum|DEFault",
	                  "SOURce1:VOLTage:LOW{0}"                       : "<voltage>|MINimum|MAXimum|DEFault",
	                  "SOURce1:VOLTage:LIMit:HIGH{0}"                : "<voltage>|MINimum|MAXimum|DEFault",
	                  "SOURce1:VOLTage:LIMit:LOW{0}"                 : "<voltage>|MINimum|MAXimum|DEFault",
	                  "SOURce1:VOLTage:LIMit:STATe{0}"               : "ON|1|OFF|0",
	                  "SOURce1:VOLTage:OFFSet{0}"                    : "<offset>|MINimum|MAXimum|DEFault",
	                  "SOURce1:VOLTage:RANGe:AUTO{0}"                : "OFF|0|ON|1|ONCE",
	                  "SOURce1:VOLTage:UNIT{0}"                      : "VPP|VRMS|DBM" 
	                  "OUTPut1:LOAD{0}": "<ohms>|INFinity|MINimum|MAXimum|DEFault",
                          "OUTPUT1:MODE{0}": "NORMal|GATed",
                          "OUTPut1:POLarity{0}": "NORMal|INVerted",
                          "OUTPut:SYNC{0}": "ON | 1 | OFF | 0",
                          "OUTPut1:SYNC:MODE{0}": "NORMal|CARRier|MARKer",
                          "OUTPut1:SYNC:POLarity{0}": "NORMal|INVerted",
                          "OUTPut:TRIGger{0}": "ON|1|OFF|0",
                          "OUTPut:TRIGger:SLOPe{0}": "POSitive|NEGative",
                          "OUTPut{0}": "ON|1|OFF|0" }

	settings_por_scpi_list = [ 'SOURce1:AM:STATe 0',
	                           'OUTPut1:SYNC:POLarity NORM',
	                           'SOURce1:PWM:STATe 0',
	                           'SOURce1:FUNCtion:PULSe:TRANsition:LEADing +4.000000000000000E-09',
	                           'SOURce1:FUNCtion:SQUare:PERiod +1.000000000000000E-03',
	                           'SOURce1:BURSt:INTernal:PERiod +1.000000000000000E-02',
	                           'SOURce1:PWM:INTernal:FREQuency +1.000000000000000E+01',
	                           'UNIT:ANGLe DEG',
	                           'UNIT:ARBitrary:ANGLe DEG',
	                           'SOURce1:PM:INTernal:FREQuency +1.000000000000000E+01',
	                           'SOURce1:FUNCtion:ARBitrary:FREQuency +1.600000000000000E+02',
	                           'SOURce1:FREQuency:SPAN +9.000000000000000E+02',
	                           'OUTPut1:MODE NORM',
	                           'TRIGger1:SLOPe POS',
	                           'FUNCtion:ARBitrary:BALance:GAIN +0.00000000E+000',
	                           'SOURce1:FUNCtion:NOISe:BANDwidth +1.000000000000000E+05',
	                           'SOURce1:BURSt:NCYCles +1.000000000000000E+00',
	                           'SOURce1:VOLTage:HIGH +5.000000000000000E-02',
	                           'OUTPut:TRIGger:SOURce CH1',
	                           'SOURce1:FUNCtion:ARBitrary:PTPeak +1.000000000000000E-01',
	                           'TRIGger1:SOURce IMM',
	                           'SOURce1:FSKey:SOURce INT',
	                           'SOURce1:FUNCtion:ARBitrary:SRATe +4.000000000000000E+04',
	                           'SOURce1:FUNCtion:PULSe:HOLD WIDT',
	                           'SOURce1:FREQuency:CENTer +5.500000000000000E+02',
	                           'SOURce1:SUM:SOURce INT',
	                           'INITiate1:CONTinuous 1',
	                           'SOURce1:FUNCtion SIN',
	                           'SOURce1:SWEep:HTIMe +0.000000000000000E+00',
	                           'SOURce1:FSKey:STATe 0',
	                           'TRIGger1:COUNt +1.000000000000000E+00',
	                           'SOURce1:BPSK:STATe 0',
	                           'SOURce1:SWEep:SPACing LIN',
	                           'SOURce1:FUNCtion:ARBitrary:ADVance SRAT',
	                           'SOURce1:FREQuency:STARt +1.000000000000000E+02',
	                           'SOURce1:BPSK:SOURce INT',
	                           'SOURce1:VOLTage +1.0000000000000E-01',
	                           'SOURce1:LIST:FREQuency +1.00000000E+002,+1.00000000E+003,+5.50000000E+002',
	                           'TRIGger1:LEVel +3.300000000000000E+00',
	                           'OUTPut1:SYNC:MODE NORM',
	                           'SOURce1:FUNCtion:PULSe:WIDTh +1.000000000000000E-04',
	                           'SOURce1:MARKer:POINt +1.00000000E+001',
	                           'OUTPut:TRIGger:SLOPe POS',
	                           'FUNCtion:ARBitrary:BALance:OFFSet1 +0.00000000E+000',
	                           'SOURce1:BURSt:GATE:POLarity NORM',
	                           'SOURce1:SUM:AMPLitude +1.000000000000000E-01',
	                           'SOURce1:FUNCtion:RAMP:SYMMetry +1.000000000000000E+02',
	                           'SOURce1:FUNCtion:PULSe:DCYCle +1.000000000000000E+01',
	                           'OUTPut:SYNC:SOURce CH1',
	                           'SOURce1:BURSt:MODE TRIG',
	                           'FUNCtion:ARBitrary:SKEW:STATe 0',
	                           'SOURce1:PWM:DEViation:DCYCle +1.000000000000000E+00',
	                           'SOURce1:LIST:DWELl +1.000000000000000E+00',
	                           'SOURce1:BPSK:INTernal:RATE +1.000000000000000E+01',
	                           'SOURce1:SWEep:STATe 0',
	                           'FUNCtion:ARBitrary:BALance:STATe 0',
	                           'SOURce1:VOLTage:LIMit:HIGH +5.000000000000000E+00',
	                           'SOURce1:FM:DEViation +1.000000000000000E+02',
	                           'SOURce1:FUNCtion:ARBitrary "INT:\BUILTIN\EXP_RISE.ARB"',
	                           'SOURce1:FREQuency:MODE CW',
	                           'SOURce1:FM:INTernal:FREQuency +1.000000000000000E+01',
	                           'SOURce1:AM:INTernal:FREQuency +1.000000000000000E+02',
	                           'TRIGger1:TIMer +1.000000000000000E+00',
	                           'SOURce1:PWM:SOURce INT',
	                           'SOURce1:FUNCtion:SQUare:DCYCle +5.000000000000000E+01',
	                           'SOURce1:VOLTage:UNIT VPP',
	                           'SOURce1:BURSt:STATe 0',
	                           'SOURce1:VOLTage:LIMit:STATe 0',
	                           'SOURce1:AM:INTernal:FUNCtion SIN',
	                           'FUNCtion:ARBitrary:BALance:OFFSet2 +0.00000000E+000',
	                           'SOURce1:BURSt:PHASe +0.0000000000000E+00',
	                           'SOURce1:MARKer:CYCle +2.000000000000000E+00',
	                           'SOURce1:PWM:INTernal:FUNCtion SIN',
	                           'ROSCillator:SOURce INT',
	                           'SOURce1:FUNCtion:ARBitrary:PERiod +6.250000000000000E-03',
	                           'SOURce1:FUNCtion:PULSe:TRANsition:TRAiling +4.000000000000000E-09',
	                           'SOURce1:FSKey:FREQuency +1.000000000000000E+02',
	                           'SOURce1:AM:SOURce INT',
	                           'SOURce1:SWEep:TIME +1.000000000000000E+00',
	                           'FUNCtion:ARBitrary:SKEW:TIME +0.00000000E+000',
	                           'SOURce1:BPSK:PHASe +1.800000000000000E+02',
	                           'SOURce1:AM:DSSC 0',
	                           'SOURce1:SUM:INTernal:FREQuency +1.000000000000000E+02',
	                           'SOURce1:FSKey:INTernal:RATE +1.000000000000000E+01',
	                           'SOURce1:FUNCtion:PRBS:TRANsition:BOTH +4.000000000000000E-09',
	                           'SOURce1:FM:SOURce INT',
	                           'SOURce1:VOLTage:OFFSet +0.0000000000000E+00',
	                           'TRIGger1:DELay +0.000000000000000E+00',
	                           'SOURce1:MARKer:FREQuency +5.000000000000000E+02',
	                           'OUTPut1:LOAD +5.000000000000000E+01',
	                           'OUTPut:TRIGger 0',
	                           'FORMat:BORDer NORM',
	                           'SOURce1:VOLTage:LOW -5.000000000000000E-02',
	                           'SOURce1:PHASe:MODulation +0.0000000000000E+00',
	                           'SOURce1:FUNCtion:PRBS:BRATe +1.000000000000000E+03',
	                           'SOURce1:FUNCtion:PRBS:DATA PN7',
	                           'ROSCillator:SOURce:AUTO ON',
	                           'SOURce1:VOLTage:RANGe:AUTO 1',
	                           'SOURce1:FREQuency:STOP +1.000000000000000E+03',
	                           'SOURce1:FM:INTernal:FUNCtion SIN',
	                           'OUTPut:SYNC 1',
	                           'SOURce1:VOLTage:LIMit:LOW -5.000000000000000E+00',
	                           'OUTPut1:POLarity NORM',
	                           'SOURce1:PHASe:ARBitrary +0.0000000000000E+00',
	                           'SOURce1:SWEep:RTIMe +0.000000000000000E+00',
	                           'SOURce1:AM:DEPTh +1.000000000000000E+02',
	                           'INPut:ATTenuation:STATe 1',
	                           'SOURce1:PM:SOURce INT',
	                           'DISPlay 1',
	                           'SOURce1:FREQuency +1.000000000000000E+03',
	                           'SOURce1:PM:STATe 0',
	                           'SOURce1:FM:STATe 0',
	                           'SOURce1:FUNCtion:PULSe:PERiod +1.000000000000000E-03',
	                           'SOURce1:SUM:INTernal:FUNCtion SIN',
	                           'SOURce1:PM:DEViation +1.800000000000000E+02',
	                           'SOURce1:FUNCtion:ARBitrary:FILTer STEP',
	                           'SOURce1:PWM:DEViation +1.000000000000000E-05',
	                           'SOURce1:PM:INTernal:FUNCtion SIN' 
				   'OUTPut1:LOAD +5.000000000000000E+01',
                                   'OUTPut1:MODE NORM',
                                   'OUTPut1:POLarity NORM',
                                   'OUTPut:SYNC 1',
                                   'OUTPut1:SYNC:MODE NORM',
                                   'OUTPut1:SYNC:POLarity NORM',
                                   'OUTPut:TRIGger 0',
                                   'OUTPut:TRIGger:SLOPe POS',
                                   'OUTPut 0' ]
